/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;
import Projet.Connexion;
import Projet.PatientDAO;
import Projet.PatientreportDAO;
import java.sql.*;
import net.proteanit.sql.DbUtils;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */
public class ajouterDiagnostic extends javax.swing.JFrame {
public int flag=0;
    /**
     * Creates new form ajouterDiagnostic
     */
    public ajouterDiagnostic() {
        initComponents();
        dontExist.setVisible(false);
        type.setVisible(false);
        Cmb.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomPatient = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        dontExist = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        Cmb = new javax.swing.JComboBox<>();
        CheckBoxOui = new javax.swing.JCheckBox();
        save = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NomPatient.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NomPatient.setText("ID du Patient");
        getContentPane().add(NomPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 55, 209, -1));

        search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        search.setText("Recherche");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 55, -1, -1));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 760, 46));

        dontExist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dontExist.setForeground(new java.awt.Color(255, 0, 0));
        dontExist.setText("L'ID du Patient n'éxiste pas !!");
        getContentPane().add(dontExist, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Symptôme");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 265, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Diagnostic");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 309, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Médicaments");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 353, -1, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 262, 200, -1));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 306, 200, -1));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 350, 200, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Service Requis");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 265, -1, -1));

        type.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        type.setText("Type de Service");
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 309, -1, -1));

        Cmb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Générale", "Single", "DUO" }));
        Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbActionPerformed(evt);
            }
        });
        getContentPane().add(Cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 306, -1, -1));

        CheckBoxOui.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckBoxOui.setText("OUI");
        CheckBoxOui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxOuiActionPerformed(evt);
            }
        });
        getContentPane().add(CheckBoxOui, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 263, 85, -1));

        save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save-icon--1.png"))); // NOI18N
        save.setText("Enregistrer");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 435, -1, -1));

        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        close.setText("Fermer");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add new patient background.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String idP =jTextField1.getText();
           try {
                ResultSet rs = (ResultSet) PatientDAO.chercherParId(idP);
                Table.setModel(DbUtils.resultSetToTableModel(rs));

                if (!rs.first()) {
                    dontExist.setVisible(true);
                } else {
                    dontExist.setVisible(false);
                    jTextField1.setEditable(false);
                    flag = 1;
                }

                rs.getStatement().getConnection().close(); // On ferme proprement la connexion

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erreur de Connexion");
                e.printStackTrace();
            }
    }//GEN-LAST:event_searchActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbActionPerformed

    private void CheckBoxOuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxOuiActionPerformed
        // TODO add your handling code here:
        if (CheckBoxOui.isSelected()){
            type.setVisible(true);
            Cmb.setVisible(true);
        }else{
            type.setVisible(false);
            Cmb.setVisible(false); 
        }
    }//GEN-LAST:event_CheckBoxOuiActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
         if (flag == 1) {
        String patientID = jTextField1.getText();
        String symptome = jTextField2.getText();
        String diagnostic = jTextField3.getText();
        String medicaments = jTextField4.getText();
        String serviceReq;
        String typeSer;
        
        if (CheckBoxOui.isSelected()) {
            serviceReq = "YES";
            typeSer = (String) Cmb.getSelectedItem();
        } else {
            serviceReq = "NO";
            typeSer = "";
        }
        
        boolean success = PatientreportDAO.savePatientReport(patientID, symptome, diagnostic, medicaments, serviceReq, typeSer);
        
        if (success) {
            JOptionPane.showMessageDialog(null, "Enregistré avec succès");
            setVisible(false);
            new ajouterDiagnostic().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Erreur d'enregistrement");
        }
    } else {
        JOptionPane.showMessageDialog(null, "L'ID du patient est vide");
    }
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajouterDiagnostic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajouterDiagnostic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajouterDiagnostic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajouterDiagnostic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajouterDiagnostic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxOui;
    private javax.swing.JComboBox<String> Cmb;
    private javax.swing.JLabel NomPatient;
    private javax.swing.JTable Table;
    private javax.swing.JButton close;
    private javax.swing.JLabel dontExist;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
