/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import interfaces.ajouterDiagnostic;
import interfaces.ajouterPatient;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class home extends javax.swing.JFrame {
public int i=0;
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPatient = new javax.swing.JButton();
        addDiagnosis = new javax.swing.JButton();
        updatePatient = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        patientHistory = new javax.swing.JButton();
        hospitalInfo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addPatient.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add new patient.png"))); // NOI18N
        addPatient.setText(" Ajouter un patient");
        addPatient.setPreferredSize(new java.awt.Dimension(240, 59));
        addPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientActionPerformed(evt);
            }
        });
        getContentPane().add(addPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 250, -1));

        addDiagnosis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addDiagnosis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add diag.png"))); // NOI18N
        addDiagnosis.setText(" Ajouter un diagnostic");
        addDiagnosis.setPreferredSize(new java.awt.Dimension(240, 59));
        addDiagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDiagnosisActionPerformed(evt);
            }
        });
        getContentPane().add(addDiagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 250, -1));

        updatePatient.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updatePatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_update_details.png"))); // NOI18N
        updatePatient.setText("Modifie un Patient");
        updatePatient.setPreferredSize(new java.awt.Dimension(240, 59));
        updatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePatientActionPerformed(evt);
            }
        });
        getContentPane().add(updatePatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 250, -1));

        logOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        logOut.setText("   LogOUT");
        logOut.setPreferredSize(new java.awt.Dimension(240, 59));
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        getContentPane().add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 250, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/two arrow.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 70));

        patientHistory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_history1.png"))); // NOI18N
        patientHistory.setText("Historique du patient");
        patientHistory.setPreferredSize(new java.awt.Dimension(240, 59));
        patientHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(patientHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 250, -1));

        hospitalInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hospitalInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_hospital_information.png"))); // NOI18N
        hospitalInfo.setText("Information d'Hôpital");
        hospitalInfo.setPreferredSize(new java.awt.Dimension(240, 59));
        hospitalInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalInfoActionPerformed(evt);
            }
        });
        getContentPane().add(hospitalInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 250, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePatientActionPerformed
        // TODO add your handling code here:
        new modifierPatient().setVisible(true);
    }//GEN-LAST:event_updatePatientActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Voulez-vous vraiment quitter!?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new login_1().setVisible(true);
        }
    }//GEN-LAST:event_logOutActionPerformed

    private void addPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientActionPerformed
        // TODO add your handling code here:
        new ajouterPatient().setVisible(true);
    }//GEN-LAST:event_addPatientActionPerformed

    private void hospitalInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalInfoActionPerformed
        // TODO add your handling code here:
        new hopitalInformations().setVisible(true);
    }//GEN-LAST:event_hospitalInfoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(i==0){
            addPatient.setLocation(90,30);
            addDiagnosis.setLocation(333,30);
            patientHistory.setLocation(576,30);
            updatePatient.setLocation(819,30);
            hospitalInfo.setLocation(1062,30);
            logOut.setLocation(1062,89);
            i=1;
        }else{
            addPatient.setLocation(10,107);
            addDiagnosis.setLocation(10,184);
            patientHistory.setLocation(10,261);
            updatePatient.setLocation(10,338);
            hospitalInfo.setLocation(10,415);
            logOut.setLocation(10,490);
            i=0;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void patientHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientHistoryActionPerformed
        // TODO add your handling code here:
        new Historique().setVisible(true);
        
    }//GEN-LAST:event_patientHistoryActionPerformed

    private void addDiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDiagnosisActionPerformed
        // TODO add your handling code here:
        new ajouterDiagnostic().setVisible(true);
    }//GEN-LAST:event_addDiagnosisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDiagnosis;
    private javax.swing.JButton addPatient;
    private javax.swing.JButton hospitalInfo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logOut;
    private javax.swing.JButton patientHistory;
    private javax.swing.JButton updatePatient;
    // End of variables declaration//GEN-END:variables
}
